"""address geocode precision

Revision ID: 01fe297433d5
Revises: 4f982ca53175
Create Date: 2026-07-23 01:22:22.827324
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = '01fe297433d5'
down_revision: str | None = '4f982ca53175'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('precision', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'precision')
    # ### end Alembic commands ###
