"""tms: vehicles, documents, customers, consignments, trips

Revision ID: 1563ba9b050b
Revises: e86af99782eb
Create Date: 2026-07-21 23:12:30.826425
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1563ba9b050b'
down_revision: str | None = 'e86af99782eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('consignor', 'consignee', 'both', name='customer_role'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('lr_counters',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'year')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.Enum('truck', 'tempo', 'trailer', 'container', 'tanker', 'tipper', 'pickup', 'other', name='vehicle_type'), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=60), nullable=True),
    sa.Column('capacity_kg', sa.Integer(), nullable=True),
    sa.Column('chassis_number', sa.String(length=40), nullable=True),
    sa.Column('engine_number', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'registration_number', name='uq_vehicle_reg_per_org')
    )
    op.create_index(op.f('ix_vehicles_organization_id'), 'vehicles', ['organization_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('line1', sa.String(length=250), nullable=False),
    sa.Column('line2', sa.String(length=250), nullable=True),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('place_name', sa.String(length=400), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_index('ix_addresses_geom', 'addresses', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_addresses_organization_id'), 'addresses', ['organization_id'], unique=False)
    op.create_table('driver_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('driving_licence', 'aadhaar', 'pan', 'police_verification', 'medical_certificate', 'address_proof', 'photo', 'other', name='driver_doc_type'), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('issuer', sa.String(length=120), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_documents_driver_id'), 'driver_documents', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_documents_expires_on'), 'driver_documents', ['expires_on'], unique=False)
    op.create_table('vehicle_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('rc', 'insurance', 'puc', 'fitness', 'permit_national', 'permit_state', 'road_tax', 'other', name='vehicle_doc_type'), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('issuer', sa.String(length=120), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_expires_on'), 'vehicle_documents', ['expires_on'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_table('consignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('lr_number', sa.String(length=40), nullable=False),
    sa.Column('consignor_id', sa.UUID(), nullable=False),
    sa.Column('consignor_address_id', sa.UUID(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('consignee_address_id', sa.UUID(), nullable=False),
    sa.Column('goods_description', sa.String(length=500), nullable=False),
    sa.Column('hsn_code', sa.String(length=12), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('declared_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('is_hazardous', sa.Boolean(), nullable=False),
    sa.Column('eway_bill_number', sa.String(length=20), nullable=True),
    sa.Column('eway_bill_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('freight_terms', sa.Enum('paid', 'to_pay', 'tbb', name='freight_terms'), nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'booked', 'in_transit', 'delivered', 'cancelled', name='consignment_status'), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignee_address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consignee_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consignor_address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consignor_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'lr_number', name='uq_lr_per_org')
    )
    op.create_index(op.f('ix_consignments_organization_id'), 'consignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consignments_status'), 'consignments', ['status'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('consignment_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('planned', 'assigned', 'started', 'in_transit', 'at_destination', 'delivered', 'cancelled', name='trip_status'), nullable=False),
    sa.Column('route_distance_m', sa.Float(), nullable=True),
    sa.Column('route_duration_s', sa.Float(), nullable=True),
    sa.Column('route_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('route_alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('route_summary', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_consignment_id'), 'trips', ['consignment_id'], unique=False)
    op.create_index('ix_trips_org_scheduled', 'trips', ['organization_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_organization_id'), 'trips', ['organization_id'], unique=False)
    op.create_index(op.f('ix_trips_scheduled_start'), 'trips', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_table('proof_of_delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('receiver_name', sa.String(length=150), nullable=False),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('otp_hash', sa.String(length=64), nullable=True),
    sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_url', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_table('tracking_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('party', sa.Enum('consignor', 'consignee', name='tracking_party'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'party', name='uq_tracking_link_party')
    )
    op.create_index(op.f('ix_tracking_links_token'), 'tracking_links', ['token'], unique=True)
    op.create_index(op.f('ix_tracking_links_trip_id'), 'tracking_links', ['trip_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tracking_link_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'sms', 'whatsapp', 'manual', name='notify_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'skipped', name='notify_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_trip_id'), 'notification_log', ['trip_id'], unique=False)
    op.add_column('drivers', sa.Column('licence_number', sa.String(length=30), nullable=True))
    op.add_column('drivers', sa.Column('licence_class', sa.String(length=30), nullable=True))
    op.add_column('drivers', sa.Column('licence_issuing_rto', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('licence_expires_on', sa.Date(), nullable=True))
    op.add_column('drivers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('drivers', sa.Column('blood_group', sa.String(length=5), nullable=True))
    op.add_column('drivers', sa.Column('address', sa.String(length=400), nullable=True))
    op.add_column('drivers', sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
    op.add_column('drivers', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('drivers', sa.Column('aadhaar_last4', sa.String(length=4), nullable=True))
    op.add_column('drivers', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('drivers', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('drivers', sa.Column('joined_on', sa.Date(), nullable=True))
    op.create_index(op.f('ix_drivers_licence_expires_on'), 'drivers', ['licence_expires_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_licence_expires_on'), table_name='drivers')
    op.drop_column('drivers', 'joined_on')
    op.drop_column('drivers', 'photo_url')
    op.drop_column('drivers', 'pan_number')
    op.drop_column('drivers', 'aadhaar_last4')
    op.drop_column('drivers', 'emergency_contact_phone')
    op.drop_column('drivers', 'emergency_contact_name')
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'blood_group')
    op.drop_column('drivers', 'date_of_birth')
    op.drop_column('drivers', 'licence_expires_on')
    op.drop_column('drivers', 'licence_issuing_rto')
    op.drop_column('drivers', 'licence_class')
    op.drop_column('drivers', 'licence_number')
    op.drop_index(op.f('ix_notification_log_trip_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_tracking_links_trip_id'), table_name='tracking_links')
    op.drop_index(op.f('ix_tracking_links_token'), table_name='tracking_links')
    op.drop_table('tracking_links')
    op.drop_table('proof_of_delivery')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_scheduled_start'), table_name='trips')
    op.drop_index(op.f('ix_trips_organization_id'), table_name='trips')
    op.drop_index('ix_trips_org_scheduled', table_name='trips')
    op.drop_index(op.f('ix_trips_consignment_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_consignments_status'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_organization_id'), table_name='consignments')
    op.drop_table('consignments')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_expires_on'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_index(op.f('ix_driver_documents_expires_on'), table_name='driver_documents')
    op.drop_index(op.f('ix_driver_documents_driver_id'), table_name='driver_documents')
    op.drop_table('driver_documents')
    op.drop_index(op.f('ix_addresses_organization_id'), table_name='addresses')
    op.drop_index('ix_addresses_geom', table_name='addresses', postgresql_using='gist')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_vehicles_organization_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('lr_counters')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
