"""vehicle document original filename

Revision ID: 2a584d49c099
Revises: f45dc6db5b10
Create Date: 2026-07-22 19:10:38.552497
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = '2a584d49c099'
down_revision: str | None = 'f45dc6db5b10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_documents', sa.Column('file_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_documents', 'file_name')
    # ### end Alembic commands ###
