"""enforce flow: device belongs to vehicle, ping belongs to trip

Revision ID: 3b7111b218df
Revises: 1563ba9b050b
Create Date: 2026-07-22 00:13:22.923626
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = '3b7111b218df'
down_revision: str | None = '1563ba9b050b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devices_vehicle_id'), 'devices', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.add_column('location_pings', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_location_pings_trip_id'), 'location_pings', ['trip_id'], unique=False)
    op.create_foreign_key(None, 'location_pings', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location_pings', type_='foreignkey')
    op.drop_index(op.f('ix_location_pings_trip_id'), table_name='location_pings')
    op.drop_column('location_pings', 'trip_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_vehicle_id'), table_name='devices')
    op.drop_column('devices', 'vehicle_id')
    # ### end Alembic commands ###
