"""driver photo and document scans

Revision ID: 4f982ca53175
Revises: 67ef36588ef7
Create Date: 2026-07-22 19:37:59.511463
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = '4f982ca53175'
down_revision: str | None = '67ef36588ef7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_documents', sa.Column('file_name', sa.String(length=200), nullable=True))
    op.add_column('drivers', sa.Column('licence_file_url', sa.String(length=500), nullable=True))
    op.add_column('drivers', sa.Column('licence_file_name', sa.String(length=200), nullable=True))
    op.add_column('drivers', sa.Column('photo_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'photo_name')
    op.drop_column('drivers', 'licence_file_name')
    op.drop_column('drivers', 'licence_file_url')
    op.drop_column('driver_documents', 'file_name')
    # ### end Alembic commands ###
