"""org letterhead and consignment document scans

Revision ID: bc8b0d979092
Revises: 01fe297433d5
Create Date: 2026-07-23 19:00:51.484045
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = 'bc8b0d979092'
down_revision: str | None = '01fe297433d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignments', sa.Column('eway_bill_file_url', sa.String(length=500), nullable=True))
    op.add_column('consignments', sa.Column('eway_bill_file_name', sa.String(length=200), nullable=True))
    op.add_column('consignments', sa.Column('invoice_file_url', sa.String(length=500), nullable=True))
    op.add_column('consignments', sa.Column('invoice_file_name', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('legal_name', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('organizations', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('organizations', sa.Column('address_line', sa.String(length=300), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('organizations', sa.Column('transporter_id', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('lr_terms', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'lr_terms')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'transporter_id')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'pincode')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line')
    op.drop_column('organizations', 'pan')
    op.drop_column('organizations', 'gstin')
    op.drop_column('organizations', 'legal_name')
    op.drop_column('consignments', 'invoice_file_name')
    op.drop_column('consignments', 'invoice_file_url')
    op.drop_column('consignments', 'eway_bill_file_name')
    op.drop_column('consignments', 'eway_bill_file_url')
    # ### end Alembic commands ###
