"""initial schema

Revision ID: e86af99782eb
Revises: 
Create Date: 2026-07-21 12:56:58.725164
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e86af99782eb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required before any geography column can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_organization_id'), 'drivers', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'tracker', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', name='device_status'), nullable=False),
    sa.Column('enrollment_code_hash', sa.String(length=64), nullable=True),
    sa.Column('enrollment_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_driver_id'), 'devices', ['driver_id'], unique=False)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_index('ix_devices_org_status', 'devices', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_token_hash'), 'devices', ['token_hash'], unique=True)
    op.create_table('location_pings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_seq', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('altitude_accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('bearing_deg', sa.Float(), nullable=True),
    sa.Column('activity', sa.Enum('still', 'walking', 'running', 'cycling', 'driving', 'unknown', name='activity_type'), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=True),
    sa.Column('network_status', sa.Enum('wifi', 'cellular', 'offline', 'unknown', name='network_status'), nullable=False),
    sa.Column('is_mock_location', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('integrity_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_seq', name='uq_ping_device_seq')
    )
    op.create_index('ix_pings_device_recorded', 'location_pings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_pings_geom', 'location_pings', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_pings_org_recorded', 'location_pings', ['organization_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pings_org_recorded', table_name='location_pings')
    op.drop_index('ix_pings_geom', table_name='location_pings', postgresql_using='gist')
    op.drop_index('ix_pings_device_recorded', table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_devices_token_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index('ix_devices_org_status', table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_driver_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drivers_organization_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('organizations')
    # ### end Alembic commands ###
