"""driver login credentials

Revision ID: f45dc6db5b10
Revises: 3b7111b218df
Create Date: 2026-07-22 00:16:19.600292
"""

from collections.abc import Sequence

import geoalchemy2  # noqa: F401  (geography columns render as geoalchemy2.*)
import sqlalchemy as sa
from alembic import op


revision: str = 'f45dc6db5b10'
down_revision: str | None = '3b7111b218df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('login_id', sa.String(length=20), nullable=True))
    op.add_column('drivers', sa.Column('hashed_password', sa.String(length=128), nullable=True))
    op.add_column('drivers', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.add_column('drivers', sa.Column('password_reset_token_hash', sa.String(length=64), nullable=True))
    op.add_column('drivers', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('drivers', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_drivers_login_id'), 'drivers', ['login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_login_id'), table_name='drivers')
    op.drop_column('drivers', 'last_login_at')
    op.drop_column('drivers', 'password_reset_expires_at')
    op.drop_column('drivers', 'password_reset_token_hash')
    op.drop_column('drivers', 'must_change_password')
    op.drop_column('drivers', 'hashed_password')
    op.drop_column('drivers', 'login_id')
    # ### end Alembic commands ###
